CREATE TABLE RATING (
    CATEGORY VARCHAR2(20) CHECK (CATEGORY IN ('VOCAL', 'RAP', 'DANCE')),
    TRAINEE_ID NUMBER REFERENCES TRAINEE(ID),
    GRADE VARCHAR2(1) DEFAULT 'F' CHECK (GRADE BETWEEN 'A' AND 'F'),
    CONSTRAINT RATING_CONSTRAINT PRIMARY KEY (CATEGORY, TRAINEE_ID)
)